### ISSUE TITLE
Loading generated files at runtime fails with "Cannot find module 'vueify/lib/insert-css'"

### ISSUE THREAD

**Issue by whitelynx** [SkewedAspect/grunt-vueify#1]
Full error as given in Electron console:

```
module.js:340 Uncaught Error: Cannot find module 'vueify/lib/insert-css'
```

npm version 2.14.12
node version 4.3.1
electron version 0.36.1

**Comment by whitelynx** [comment]
It looks like this is due to `vueify` being installed as a dependency of `grunt-vueify`, and this version of `npm` not flattening `node_modules` like newer versions do. If we make `vueify` a peer dependency instead, that would mean it'd be guaranteed to be accessible to the running app, but that would also require changes to any projects using `grunt-vueify`.

For now, explicitly installing `vueify` in the main project is a workaround, but there is the potential for the versions of `vueify` installed at the top level and inside `grunt-vueify` to become out of sync... it seems like a peer dependency may be the best long-term solution.

**Comment by wotermelon** [comment]
@whitelynx How did you solve this? I met the same problem.please help

**Comment by whitelynx** [comment]
@zhangmingze: As mentioned in my second comment, my workaround was adding `vueify` as a direct dependency of the main project... the only catch is that you need to keep an eye on the version numbers match between your project and `grunt-vueify`, or you'll end up with two different versions installed, and it likely won't work correctly.

The other workaround is to simply upgrade `npm` to the latest version, which flattens dependencies; that makes `vueify` available to the project itself.

**Comment by wotermelon** [comment]
@whitelynx thank you very much.It works well
